const GAMES = [
  {
    id: 'sudoku',
    name: 'Sudoku',
    icon: '🔢',
    category: 'daily',
    shell: 'daily',
    daily: true,
    /* #176 — the 6×6 left this entry's in-game chooser and became its own card
       (`sudokumini`). Two board sizes are two different games sharing a
       component, not one game with a setting: they deserve separate dailies,
       separate ladders and separate boards. `fixedDifficulty` is what tells the
       shared component which one it is, so the chooser never renders. */
    fixedDifficulty: 'classic',
    desc: 'The full 9×9 grid. Every row, column and box holds 1–9 exactly once.',
    tag: 'Logic',
    tagColor: GA.sky,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'tap', undo: 'free' },
    fitShell: true,
    howToPlay: [
      { title: 'Pick a board', body: 'Choose 9×9 Classic (worth double points) or the quick 6×6 Mini. The clock only starts once you pick.' },
      { title: 'Fill the grid', body: 'Tap a cell, then pick a number. Every row, column, and box must contain each number exactly once. Overwrite freely — mistakes cost steps, not the game.' },
      { title: 'Score', body: 'Faster solves with fewer steps score higher. Everyone gets the same boards today.' },
    ],
    component: SudokuGame,
  },
  {
    id: 'sudokumini',
    name: 'Sudoku Mini',
    icon: '🔡',
    category: 'daily',
    shell: 'daily',
    daily: true,
    fixedDifficulty: 'mini',
    desc: 'The quick 6×6 board — same rules, a fraction of the time.',
    tag: 'Logic',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'tap', undo: 'free' },
    fitShell: true,
    howToPlay: [
      { title: 'Fill the grid', body: 'Tap a cell, then pick a number. Every row, column and 3×2 box must contain 1–6 exactly once.' },
      { title: 'Quick by design', body: 'Six columns instead of nine — a couple of minutes rather than ten. The full 9×9 lives on its own card.' },
      { title: 'Score', body: 'Faster solves with fewer steps score higher. Everyone gets the same board today.' },
    ],
    component: SudokuGame,
  },
  {
    id: 'wordhunt',
    name: 'Word Search',
    icon: '🔤',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Find every hidden word in the letter grid.',
    tag: 'Word',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'drag', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Find the words', body: 'Drag across the letter grid to select a word — horizontally, vertically, or diagonally, forwards or backwards.' },
      { title: 'Clear the list', body: 'Find every listed word to solve the puzzle. Stray drags count as steps, so aim carefully.' },
      { title: 'Score', body: 'Faster solves with fewer steps score higher. Everyone hunts the same grid today.' },
    ],
    component: WordHuntGame,
  },
  {
    id: 'cryptowordle',
    name: 'Daily Cipher',
    icon: '🟩',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Decode a daily stack of crypto-vocabulary words — clues unlock as you go, or use a free hint.',
    tag: 'Words',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'keyboard', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Guess the word', body: 'Type a guess and submit. Green = right letter, right spot; gold = right letter, wrong spot.' },
      { title: 'Work the stack', body: "Today's puzzle is a stack of crypto words — solve one to unlock the next. Clues unlock as you go, and free hints are capped per day." },
      { title: 'Careful', body: 'Run out of guesses on any word and the day is lost — the board locks until the next UTC reset.' },
    ],
    component: CryptoWordleGame,
  },
  {
    id: 'minesweeper',
    name: 'Mine Finder Classic',
    icon: '💣',
    category: 'classic',
    shell: 'classic',
    desc: 'Clear the 8×8 grid of mines. Lock In early to bank a risk multiplier.',
    tag: 'Risk',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Clear the field', body: 'Tap to reveal a cell; numbers tell you how many mines touch it. Switch to Flag mode to mark mines — long-press always does the opposite of the current mode.' },
      { title: 'Clear around a number', body: "Once a number's mines are all flagged, tap the number to open every remaining square around it in one go." },
      { title: 'Lock in or push on', body: 'Lock In early to bank a smaller multiplier, or keep clearing for a bigger score — one mine ends the run.' },
    ],
    // Extra ☰ sheet sections beyond the registry-standard ones — here the
    // "My Best Runs" history the hidden legacy tab strip stranded.
    sheetExtras: () => [msBestRunsSection()],
    component: MinesweeperGame,
  },
  {
    id: 'mancala',
    name: 'Mancala',
    icon: '🫘',
    category: 'classic',
    shell: 'classic',
    desc: 'Classic stone-pit strategy. Outsmart your opponent by capturing more stones.',
    tag: 'Strategy',
    tagColor: GA.amber,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Sow your stones', body: 'Tap one of your pits to scoop its stones and drop them one-by-one counter-clockwise. Landing in your store banks a stone and earns another turn.' },
      { title: 'Capture', body: 'Land your last stone in an empty pit on your side to capture it plus everything opposite. Most stones banked when a side empties wins.' },
    ],
    component: MancalaGame,
    modes: ['bot', '2p', 'online'],
    supportsSave: true,
  },
  {
    id: 'chutes-ladders',
    name: 'Snakes & Ladders',
    icon: '🪜',
    category: 'classic',
    shell: 'classic',
    desc: 'Race up the board — climb ladders, dodge slides. 2-player hotseat.',
    tag: 'Board',
    tagColor: GA.lime,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Roll and race', body: 'Tap to roll the die and move up the board. Ladders lift you ahead; slides drop you back.' },
      { title: 'First to 100 wins', body: 'Play the bot, a hotseat friend, or online via room code. Win streaks climb the leaderboard.' },
    ],
    component: ChutesLaddersGame,
    modes: ['bot', '2p', 'online'],
    supportsSave: true,
    menuModePicker: true,
    variantPicker: {
      label: 'Board style',
      default: 'classic',
      options: [
        { id: 'classic', name: 'Classic' },
        {
          id: 'moksha', name: 'Moksha Patam (original)',
          note: 'The Indian original: ladders on virtues, snakes on vices — 11 vices to 5 virtues, so the climb is a slower one.',
        },
      ],
    },
    leaderboard: true,
    leaderboardOpts: { valueLabel: 'Best Streak' },
  },
  {
    id: '2048',
    name: '2048',
    icon: '🔢',
    category: 'classic',
    shell: 'classic',
    desc: 'Slide tiles to merge numbers and reach 2048.',
    tag: 'Numbers',
    tagColor: GA.amber,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'long', input: 'swipe', undo: 'none' },
    howToPlay: [
      { title: 'Slide and merge', body: 'Swipe to slide every tile. Two matching tiles merge into their sum — chase 2048 and beyond.' },
      { title: "Don't jam the board", body: 'A new tile appears after every move. The run ends when no merges are left.' },
    ],
    component: T2048Game,
    modes: ['solo', 'online'],
    preLaunchModal: true,
    leaderboard: true,
  },
  {
    id: 'knights-tour',
    name: "Knight's Tour",
    icon: '♞',
    category: 'classic',
    shell: 'classic',
    desc: "Move a chess knight to visit all 64 squares exactly once.",
    tag: 'Puzzle',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'free' },
    howToPlay: [
      { title: 'Tour the board', body: 'Move the knight in its L-shape to squares it has never visited. Visit all 64 exactly once for a full tour.' },
      { title: 'Undo freely', body: 'Stuck? Step back with Undo and try a different route — longer tours score higher.' },
    ],
    component: KnightsTourGame,
  },
  {
    id: 'snake',
    name: 'Snake',
    icon: '🐍',
    category: 'classic',
    shell: 'self',
    desc: 'Swipe to steer, eat to grow, and chase a high score without crashing.',
    tag: 'Arcade',
    tagColor: GA.lime,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'swipe', undo: 'none' },
    howToPlay: [
      { title: 'Steer the snake', body: 'Swipe (or use arrow keys) to change direction. Eat food to grow and score.' },
      { title: 'Stay alive', body: 'Hitting a wall or your own tail ends the run. Longer snakes and faster modes score more.' },
    ],
    component: SnakeGame,
  },
  {
    id: 'blockblast',
    name: 'Block Fit',
    icon: '🧱',
    category: 'classic',
    shell: 'self',
    desc: 'Drag blocks onto the grid and clear full lines. How long can you last?',
    tag: 'Puzzle',
    tagColor: GA.sky,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'drag', undo: 'none' },
    howToPlay: [
      { title: 'Place the pieces', body: 'Drag each offered block onto the grid anywhere it fits. Fill a full row or column to clear it.' },
      { title: 'Keep space open', body: 'The run ends when no offered piece fits. Multi-line clears and combos score big.' },
    ],
    component: BlockBlastGame,
    modes: ['solo', 'online'],
    preLaunchModal: true,
    leaderboard: true,
  },
  {
    id: 'diamondrush',
    name: 'Diamond Rush',
    icon: '💎',
    category: 'classic',
    shell: 'self',
    desc: 'Swap gems to line up 3+ and cascade your way to the target score.',
    tag: 'Match',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Swap to match', body: 'Tap two adjacent gems to swap them. Line up 3 or more of a kind to clear them.' },
      { title: 'Chase cascades', body: 'Cleared gems drop new ones — chains cascade for bonus points. Hit the target score before time runs out.' },
    ],
    component: DiamondRushGame,
  },
  {
    id: 'tilematching',
    name: 'Tile Match Puzzle',
    icon: '🀄',
    category: 'classic',
    shell: 'classic',
    desc: 'Click tiles off the layered board into your 7-slot bar — match three to clear them.',
    tag: 'Puzzle',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'booster' },
    howToPlay: [
      { title: 'Pick free tiles', body: 'Tap any uncovered tile to move it into your 7-slot bar. Three of a kind in the bar clear automatically.' },
      { title: 'Mind the bar', body: 'If the bar fills with no match, the round is lost. Undo, shuffle, and clear-slot boosters are limited — spend them wisely.' },
    ],
    component: TileMatchingGame,
  },
  {
    id: 'bounce',
    name: 'Bounce',
    icon: '🧱',
    category: 'classic',
    shell: 'classic',
    desc: "Smash every brick with a bouncing ball. Don't let it fall — climb the leaderboard.",
    tag: 'Arcade',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'drag', undo: 'none' },
    howToPlay: [
      { title: 'Keep it up', body: 'Drag the paddle to keep the ball in play and smash every brick.' },
      { title: 'Clear the wall', body: 'Some bricks take multiple hits. Lose the ball and the run ends — full clears score best.' },
    ],
    component: BounceGame,
  },
  {
    id: 'zuma',
    name: 'Marble Loop',
    icon: '🐸',
    category: 'classic',
    shell: 'classic',
    desc: 'Shoot colored balls to match 3 in a row before the chain reaches the skull.',
    tag: 'Arcade',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Shoot to match', body: 'Aim and tap to fire a colored ball into the moving chain. Three or more of a color clear.' },
      { title: 'Beat the chain', body: 'Clear the whole chain before it reaches the skull. Gaps and combos multiply your score.' },
    ],
    component: ZumaGame,
  },
  {
    id: 'match3',
    name: 'Match-3 Puzzle',
    icon: '🟩',
    category: 'classic',
    shell: 'classic',
    desc: 'Classic match-3 campaign: progress through 50 puzzles and climb the leaderboard.',
    tag: 'Campaign',
    tagColor: GA.amber,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'long', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Swap to match', body: 'Tap two adjacent pieces to swap. Match 3+ to clear them and rack up points.' },
      { title: 'Beat each level', body: 'Every level has a target score under move and time limits. 50 levels — progress saves as you go.' },
    ],
    component: Match3Game,
  },
  {
    id: 'hashrush',
    name: 'Hash Rush',
    icon: '⛏️',
    category: 'classic',
    shell: 'self',
    desc: 'Dodge invalid blocks, collect hash tokens — how long can your miner survive?',
    tag: 'Arcade',
    tagColor: GA.plum,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'swipe', undo: 'none' },
    howToPlay: [
      { title: 'Dodge and collect', body: 'Steer your miner between lanes — grab hash tokens, dodge the invalid blocks.' },
      { title: 'Survive', body: 'The chain speeds up the longer you last. One collision ends the run.' },
    ],
    component: HashRushGame,
    leaderboard: true,
  },
  // Phase 5 board games — online head-to-head over classic_rooms; the server
  // referees every move (rules modules in lib/board-rules.js) and wins settle
  // on the rating ladder.
  {
    id: 'checkers',
    name: 'Checkers',
    icon: '⛃',
    category: 'classic',
    shell: 'classic',
    desc: 'Classic draughts vs a friend online — jump, chain captures, crown your kings.',
    tag: 'Board',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'long', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Move diagonally', body: 'Tap your piece, then a dark square ahead of it. Jump over an adjacent enemy piece to capture it.' },
      { title: 'Chain your jumps', body: 'After a capture, the same piece may keep jumping while captures are available.' },
      { title: 'Crown kings', body: 'Reach the far row to crown a king — kings move and capture in all four diagonals. Take every enemy piece (or leave them no move) to win.' },
    ],
    component: CheckersGame,
    // #144 — local pass-and-play and Versus Bot alongside Online. Both local
    // modes referee with the SERVER'S rules module (window.boardRules) and are
    // deliberately unrated: only online head-to-head touches the ladder.
    modes: ['bot', '2p', 'online'],
    preLaunchModal: true,
  },
  {
    id: 'reversi',
    name: 'Reversi',
    icon: '⚫',
    category: 'classic',
    shell: 'classic',
    desc: 'Flip your way to a majority — outflank your opponent online.',
    tag: 'Board',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Outflank to flip', body: 'Place a disc so a straight line of enemy discs is trapped between yours — they all flip to your color.' },
      { title: 'Every move must flip', body: 'You can only play cells that flip at least one disc. No legal move? Your turn passes automatically.' },
      { title: 'Majority wins', body: 'When neither player can move, the most discs on the board wins.' },
    ],
    component: ReversiGame,
    // #144 — local pass-and-play and Versus Bot alongside Online. Both local
    // modes referee with the SERVER'S rules module (window.boardRules) and are
    // deliberately unrated: only online head-to-head touches the ladder.
    modes: ['bot', '2p', 'online'],
    preLaunchModal: true,
  },
  {
    id: 'fourinarow',
    name: 'Four in a Row',
    icon: '🔴',
    category: 'classic',
    shell: 'classic',
    desc: 'Drop discs and line up four before your opponent does.',
    tag: 'Board',
    tagColor: GA.sky,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'short', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Drop a disc', body: 'Tap a column — your disc falls to the lowest empty slot.' },
      { title: 'Line up four', body: 'Four of your discs in a row — across, down, or diagonally — wins. A full board with no line is a draw.' },
    ],
    component: FourInARowGame,
    // #144 — local pass-and-play and Versus Bot alongside Online. Both local
    // modes referee with the SERVER'S rules module (window.boardRules) and are
    // deliberately unrated: only online head-to-head touches the ladder.
    modes: ['bot', '2p', 'online'],
    preLaunchModal: true,
  },
  {
    id: 'gomoku',
    name: 'Gomoku',
    icon: '⚪',
    category: 'classic',
    shell: 'classic',
    desc: 'Five stones in a row on a 15×15 board — pure placement strategy.',
    tag: 'Board',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'medium', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Take turns placing stones', body: 'Tap an intersection to line up a stone, slide to adjust, then Place it. Stones never move once placed, so nothing commits until you confirm.' },
      { title: 'Five in a row wins', body: 'First to line up five (or more) stones — across, down, or diagonally — wins the game.' },
    ],
    component: GomokuGame,
    // #144 — local pass-and-play and Versus Bot alongside Online. Both local
    // modes referee with the SERVER'S rules module (window.boardRules) and are
    // deliberately unrated: only online head-to-head touches the ladder.
    modes: ['bot', '2p', 'online'],
    preLaunchModal: true,
  },
  {
    id: 'ludo',
    name: 'Ludo',
    icon: '🎲',
    category: 'classic',
    shell: 'classic',
    desc: 'Race all four tokens home — roll sixes, capture rivals, play it safe on the stars.',
    tag: 'Board',
    tagColor: GA.lime,
    manifest: { scoreDirection: 'higher', tieBreak: 'first-to-score', sessionLength: 'long', input: 'tap', undo: 'none' },
    howToPlay: [
      { title: 'Roll, then move', body: 'Roll the die, then pick a token — tap it on the board, or use the list of your legal moves below it. You need a 6 to leave base — and a 6 earns another roll.' },
      { title: 'Capture and stay safe', body: "Land on an opponent's token to send it back to base. Star cells are safe — no captures there." },
      { title: 'Bring all four home', body: 'Race around the board into your home column. You need an exact roll to finish each token; first with all four home wins.' },
    ],
    component: LudoGame,
    // #144 — local pass-and-play and Versus Bot alongside Online. Both local
    // modes referee with the SERVER'S rules module (window.boardRules) and are
    // deliberately unrated: only online head-to-head touches the ladder.
    modes: ['bot', '2p', 'online'],
    preLaunchModal: true,
  },
  {
    id: 'tilematchingdaily',
    name: 'Daily Tile Match Puzzle',
    icon: '🀄',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'A different layered board every day — clear it before the tray jams.',
    tag: 'Puzzle',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'tap', undo: 'booster' },
    fitShell: true,
    howToPlay: [
      { title: 'Pick free tiles', body: 'Tap any uncovered tile to move it into your 7-slot tray. Three of a kind clear automatically. The board shape changes every day and gets harder toward the weekend.' },
      { title: 'Mind the tray', body: 'There are 12 tile types and only 7 slots — fill the tray with seven different icons and the day is lost. Today\'s board is always solvable in at least one order, but plenty of orders lose.' },
      { title: 'Strategy', body: 'Work the TOP layers first: a triple is usually split across levels, so the tile you need last is often buried under the easy ones. Before taking a tile, check that its two partners are reachable — and keep at least two tray slots free so a forced pick never jams you.' },
      { title: 'Boosters and scoring', body: 'Undo, shuffle and clear-slot are limited per day and now genuinely matter. Your score rewards a fast, efficient clear with boosters left unspent — not just tapping quickly.' },
    ],
    component: TileMatchingDailyGame,
  },
  // Phase 6 Lane A dailies — shared card/tile engine games. All daily,
  // shell 'daily', tier B server-side (see GAME_REGISTRY). Names follow the
  // spec's IP-hygiene rules: generic public-domain game names only.
  {
    id: 'klondike',
    name: 'Klondike Solitaire',
    icon: '🃏',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'The classic patience deal — everyone plays the same shuffle today.',
    tag: 'Cards',
    tagColor: GA.sky,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'tap', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Build down, alternate colors', body: 'Drag a card (or tap it, then its destination). Tableau piles build downward in alternating colors; only a King moves to an empty column — empty columns show a faint K. An illegal move tells you why.' },
      { title: 'Send cards home', body: 'Foundations build up by suit from Ace to King — each suit has its own slot, marked on the board. Tap a selected top card again to auto-send it home. Tap the stock to draw; it recycles when empty.' },
      { title: 'Score', body: 'Fill all four foundations to win. Fewer moves and faster solves score higher — same deal for everyone today.' },
      { title: 'Stuck?', body: 'Give up closes the day at zero and reveals the deal. It does NOT break your streak.' },
    ],
    component: KlondikeGame,
  },
  {
    id: 'spider',
    name: 'Spider Solitaire',
    icon: '🕷️',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'One-suit spider: build eight King-to-Ace runs to clear the board.',
    tag: 'Cards',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'long', input: 'tap', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Move descending runs', body: 'Drag a face-up card (or tap it, then its destination) to move it and the run below onto a column whose top card is one rank higher, or any empty column.' },
      { title: 'Complete runs', body: 'A full King-to-Ace run clears off the board. Clear eight runs to win. Deal a fresh row of ten from the stock when you\'re stuck.' },
      { title: 'Score', body: 'Fewer moves and faster clears score higher. Everyone gets the same 104-card deal today.' },
      { title: 'Stuck?', body: 'Give up closes the day at zero and reveals the deal. It does NOT break your streak.' },
    ],
    component: SpiderGame,
  },
  {
    id: 'mahjongsol',
    name: 'Mahjong Solitaire',
    icon: '🎴',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Clear the layered tile pyramid by pairing free matching tiles.',
    tag: 'Tiles',
    tagColor: GA.teal,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'tap', undo: 'booster' },
    fitShell: true,
    howToPlay: [
      { title: 'Pair free tiles', body: 'A tile is free when nothing rests on top of it and its left or right side is open. Tap two matching free tiles to clear them — a blocked tile shakes to say so.' },
      { title: 'Plan your order', body: 'Today\'s deal is always solvable in at least one order — but a careless order can dead-end you. The board shape rotates through the week, gentlest on Monday and hardest at the weekend.' },
      { title: 'Three lifelines', body: 'Three undos, three hints and one shuffle. The shuffle is guaranteed to leave the board solvable from where you are — but every lifeline costs points at the end.' },
      { title: 'Score', body: 'Clear all 60 tiles to win. Clearing upper-layer tiles is worth more, and consecutive matches with no hint build a chain bonus. Run out of moves with no shuffle left and the day is lost.' },
    ],
    component: MahjongSolitaireGame,
  },
  {
    id: 'nonogram',
    name: 'Nonogram',
    icon: '🖼️',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Fill the 8×8 grid so every row and column matches its number clues.',
    tag: 'Logic',
    tagColor: GA.plum,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'tap', undo: 'free' },
    fitShell: true,
    howToPlay: [
      { title: 'Read the clues', body: 'Each number is a run of filled cells in that row or column, in order, with at least one gap between runs.' },
      { title: 'Fill and mark', body: 'Use ⬛ Fill for cells you\'re sure of and ✗ Mark for cells that must stay empty. Both toggle freely — mistakes cost steps, not the day.' },
      { title: 'Score', body: 'The puzzle solves when every clue is satisfied. Fewer taps and faster solves score higher.' },
    ],
    component: NonogramGame,
  },
  {
    id: 'minefinder',
    name: 'Mine Finder',
    icon: '🚩',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Sweep the daily minefield — one wrong tap ends the day.',
    tag: 'Risk',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'tap', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Count the numbers', body: 'Each number counts the mines touching that cell. A safe opening area is revealed for you — work outward from it.' },
      { title: 'Dig or flag', body: 'The big button under the board switches between ⛏ Dig and 🚩 Flag. A long-press always does the OPPOSITE of the current mode, so you never have to switch for a single cell. On a desktop, right-click flags.' },
      { title: 'Clear around a number', body: 'Once a number has exactly that many flags around it, tap the number to uncover all its remaining neighbours at once. Flag it wrong and you\'ll hit the mine — the number pulses if the flag count doesn\'t match yet.' },
      { title: 'Careful', body: 'Reveal all 71 safe cells to win. Tap a mine and the day is lost — everyone sweeps the same field today.' },
    ],
    component: MineFinderGame,
  },
  {
    id: 'anagrams',
    name: 'Anagram Sprint',
    icon: '🔀',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Unscramble five words back-to-back against the clock.',
    tag: 'Word',
    tagColor: GA.amber,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'tap', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Rebuild the word', body: 'Tap the scrambled letters in order to build your answer; tap a slot (or ⌫) to take a letter back.' },
      { title: 'Five in a row', body: 'Solve all five words — two 5-letter, two 6-letter, and one 7-letter. Wrong submissions cost tries, never the day.' },
      { title: 'Score', body: 'Fewer tries and faster sprints score higher. Everyone unscrambles the same five words today.' },
    ],
    component: AnagramsGame,
  },
  {
    id: 'cratepush',
    name: 'Crate Push',
    icon: '📦',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Push every crate onto a goal pad in today\'s warehouse.',
    tag: 'Puzzle',
    tagColor: GA.lime,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'medium', input: 'tap', undo: 'free' },
    fitShell: true,
    howToPlay: [
      { title: 'Push, never pull', body: 'Move with the arrows (or arrow keys). Walking into a crate pushes it one cell — you can\'t pull, and you can\'t push two at once.' },
      { title: 'Don\'t get cornered', body: 'A crate shoved against a wall corner may be stuck for good. Undo steps back freely, or Restart the room.' },
      { title: 'Score', body: 'Park every crate on a green pad to win. Fewer moves and faster solves score higher.' },
    ],
    component: CratePushGame,
  },
  {
    id: 'dropstack',
    name: 'Drop Stack',
    icon: '🧊',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Survive today\'s falling-block sequence — the speed climbs as you clear.',
    tag: 'Puzzle',
    tagColor: GA.violet,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'drag', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Pieces fall on their own', body: 'Gravity is on from the first piece. Drag your finger across the well to slide it, tap to rotate, and swipe down (or hit ⬇ Drop) to slam it home. Arrow keys work on a desktop.' },
      { title: 'Clear lines, climb levels', body: 'Complete a full row to clear it — 100 points for one line up to 700 for four, all multiplied by your level. Every 10 lines the level goes up and pieces fall faster.' },
      { title: 'Next and Hold', body: 'The panel beside the well shows the next three pieces. Tap Hold to bank the current piece for later — once per piece, and tapping it again swaps the banked one back in.' },
      { title: 'Survive the sequence', body: 'Everyone gets the same 200-piece order today. Clear the whole bag to win; stack past the top and the day is lost.' },
    ],
    component: DropStackGame,
  },
  {
    id: 'wordsprint',
    name: 'Word Sprint',
    icon: '🔠',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: 'Trace neighboring letters and find every word you can in 90 seconds.',
    tag: 'Word',
    tagColor: GA.sky,
    manifest: { scoreDirection: 'higher', tieBreak: 'score-then-time', sessionLength: 'short', input: 'tap', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Trace a word', body: 'Tap letters that touch — sideways or diagonally — to spell a word. Tap the last letter again (or Submit) to bank it.' },
      { title: 'Rack up words', body: '3+ letters, no reusing a tile within one word. Longer words score much more: 3 letters is 30, 7 letters is 300.' },
      { title: 'Beat the clock', body: '90 seconds on the clock. Everyone gets the same grid today — most points wins the board.' },
    ],
    component: WordSprintGame,
  },
  {
    id: 'snakedaily',
    name: 'Daily Snake',
    icon: '🐍',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: "Today's apple trail — eat 20 apples without crashing. One run per day.",
    tag: 'Arcade',
    tagColor: GA.lime,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'swipe', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Steer the snake', body: 'Swipe (or use arrow keys) to change direction. The apples appear in the same order for everyone today.' },
      { title: 'Eat 20 to win', body: 'Reach 20 apples and the day is yours — faster runs score higher. Hit a wall or your tail and the day is lost.' },
      { title: 'One run', body: 'This is the daily challenge — no restarts. Warm up in the free-play Snake first if you like.' },
    ],
    component: DailySnakeGame,
  },
  {
    id: 'bouncedaily',
    name: 'Daily Bounce',
    icon: '🧱',
    category: 'daily',
    shell: 'daily',
    daily: true,
    desc: "Today's brick wall, three balls — clear it faster than everyone else.",
    tag: 'Arcade',
    tagColor: GA.coral,
    manifest: { scoreDirection: 'higher', tieBreak: 'time-then-steps', sessionLength: 'short', input: 'drag', undo: 'none' },
    fitShell: true,
    howToPlay: [
      { title: 'Keep it up', body: 'Drag to move the paddle; tap to launch. Everyone plays the exact same wall today.' },
      { title: 'Clear the wall', body: 'Green bricks take one hit, gold two, red three. Clear every brick to win — spare balls and speed boost your score.' },
      { title: 'Catch the power-ups', body: 'Bricks marked with a white pip drop a capsule: 🔄 multi-ball, ⬆️ wider paddle, 🐢 slower ball, ⚡ laser. Same bricks drop the same capsules for everyone today.' },
      { title: 'Three balls', body: 'Lose all three and the day is lost. Warm up in free-play Bounce first if you like.' },
    ],
    component: DailyBounceGame,
  },
];
